#@ load("@ytt:overlay", "overlay")
#@data/values
---
#@overlay/match missing_ok=True
images:
  routecontroller: cloudfoundry/routecontroller@sha256:df5a430a4c71e3317914265bbbfa96958763d9a65bb5f9b085c81f2df0bc89a0
