#@ load("@ytt:overlay", "overlay")
#@data/values
---
#@overlay/match missing_ok=True
images:
  routecontroller: "index.docker.io/cloudfoundry/routecontroller@sha256:983b70fca4fff9eae1c927ef10d899151b2f0f2e449bf90613fc11eb65543a0c"
