#@ load("@ytt:overlay", "overlay")
#@data/values
---
#@overlay/match missing_ok=True
images:
  routecontroller: cloudfoundry/routecontroller@sha256:547a0939ab61bcac7a24f371f7eba0ba5ee287a88d2d45478fcc88be1f524e73
