platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-for-k8s-dind

params:
  DOCKERHUB_USERNAME: ((dockerhub.username))
  DOCKERHUB_PASSWORD: ((dockerhub.password))
  GIT_COMMIT_EMAIL: cf-release-integration@pivotal.io
  GIT_COMMIT_USERNAME: "relint-ci"

inputs:
  - name: cf-k8s-networking

outputs:
  - name: updated-cf-k8s-networking

run:
  path: cf-k8s-networking/ci/tasks/build-image/task.sh
