#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

set -e

echo "Regenerating sweet sweet istio config 🎩🎩🎩"

pushd "$(git rev-parse --show-toplevel)" > /dev/null
  ./config/istio/build.sh
  if [[ -n "$(git diff -- ./config/istio-generated/xxx-generated-istio.yaml)" ]]; then
    echo "Generated istio config has been changed. Validate and add before committing.";
    exit 1
  fi
popd > /dev/null

echo "No changes to istio config! ✨✨✨"
