#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

echo "Regenerating sweet sweet istio config 🎩🎩🎩"

pushd $(git rev-parse --show-toplevel)
  ./config/istio/build.sh
  git add config/istio-generated/xxx-generated-istio.yaml
popd

echo "Regenerated and added! ✨✨✨"
