// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"code.cloudfoundry.org/cf-k8s-networking/cfroutesync/models"
	"code.cloudfoundry.org/cf-k8s-networking/cfroutesync/webhook"
)

type K8sResourceBuilder struct {
	BuildStub        func([]models.Route, webhook.Template) []webhook.K8sResource
	buildMutex       sync.RWMutex
	buildArgsForCall []struct {
		arg1 []models.Route
		arg2 webhook.Template
	}
	buildReturns struct {
		result1 []webhook.K8sResource
	}
	buildReturnsOnCall map[int]struct {
		result1 []webhook.K8sResource
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *K8sResourceBuilder) Build(arg1 []models.Route, arg2 webhook.Template) []webhook.K8sResource {
	var arg1Copy []models.Route
	if arg1 != nil {
		arg1Copy = make([]models.Route, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.buildMutex.Lock()
	ret, specificReturn := fake.buildReturnsOnCall[len(fake.buildArgsForCall)]
	fake.buildArgsForCall = append(fake.buildArgsForCall, struct {
		arg1 []models.Route
		arg2 webhook.Template
	}{arg1Copy, arg2})
	fake.recordInvocation("Build", []interface{}{arg1Copy, arg2})
	fake.buildMutex.Unlock()
	if fake.BuildStub != nil {
		return fake.BuildStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.buildReturns
	return fakeReturns.result1
}

func (fake *K8sResourceBuilder) BuildCallCount() int {
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	return len(fake.buildArgsForCall)
}

func (fake *K8sResourceBuilder) BuildCalls(stub func([]models.Route, webhook.Template) []webhook.K8sResource) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = stub
}

func (fake *K8sResourceBuilder) BuildArgsForCall(i int) ([]models.Route, webhook.Template) {
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	argsForCall := fake.buildArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *K8sResourceBuilder) BuildReturns(result1 []webhook.K8sResource) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = nil
	fake.buildReturns = struct {
		result1 []webhook.K8sResource
	}{result1}
}

func (fake *K8sResourceBuilder) BuildReturnsOnCall(i int, result1 []webhook.K8sResource) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = nil
	if fake.buildReturnsOnCall == nil {
		fake.buildReturnsOnCall = make(map[int]struct {
			result1 []webhook.K8sResource
		})
	}
	fake.buildReturnsOnCall[i] = struct {
		result1 []webhook.K8sResource
	}{result1}
}

func (fake *K8sResourceBuilder) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *K8sResourceBuilder) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ webhook.K8sResourceBuilder = new(K8sResourceBuilder)
