// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"net/http"
	"sync"
)

type JSONClient struct {
	MakeRequestStub        func(*http.Request, interface{}) error
	makeRequestMutex       sync.RWMutex
	makeRequestArgsForCall []struct {
		arg1 *http.Request
		arg2 interface{}
	}
	makeRequestReturns struct {
		result1 error
	}
	makeRequestReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *JSONClient) MakeRequest(arg1 *http.Request, arg2 interface{}) error {
	fake.makeRequestMutex.Lock()
	ret, specificReturn := fake.makeRequestReturnsOnCall[len(fake.makeRequestArgsForCall)]
	fake.makeRequestArgsForCall = append(fake.makeRequestArgsForCall, struct {
		arg1 *http.Request
		arg2 interface{}
	}{arg1, arg2})
	fake.recordInvocation("MakeRequest", []interface{}{arg1, arg2})
	fake.makeRequestMutex.Unlock()
	if fake.MakeRequestStub != nil {
		return fake.MakeRequestStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.makeRequestReturns
	return fakeReturns.result1
}

func (fake *JSONClient) MakeRequestCallCount() int {
	fake.makeRequestMutex.RLock()
	defer fake.makeRequestMutex.RUnlock()
	return len(fake.makeRequestArgsForCall)
}

func (fake *JSONClient) MakeRequestCalls(stub func(*http.Request, interface{}) error) {
	fake.makeRequestMutex.Lock()
	defer fake.makeRequestMutex.Unlock()
	fake.MakeRequestStub = stub
}

func (fake *JSONClient) MakeRequestArgsForCall(i int) (*http.Request, interface{}) {
	fake.makeRequestMutex.RLock()
	defer fake.makeRequestMutex.RUnlock()
	argsForCall := fake.makeRequestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *JSONClient) MakeRequestReturns(result1 error) {
	fake.makeRequestMutex.Lock()
	defer fake.makeRequestMutex.Unlock()
	fake.MakeRequestStub = nil
	fake.makeRequestReturns = struct {
		result1 error
	}{result1}
}

func (fake *JSONClient) MakeRequestReturnsOnCall(i int, result1 error) {
	fake.makeRequestMutex.Lock()
	defer fake.makeRequestMutex.Unlock()
	fake.MakeRequestStub = nil
	if fake.makeRequestReturnsOnCall == nil {
		fake.makeRequestReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.makeRequestReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *JSONClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.makeRequestMutex.RLock()
	defer fake.makeRequestMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *JSONClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
