{
 "title": "Indicators",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "App-Destined Ingress Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "requests per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_cf_requests_total{destination_workload_namespace=\"cf-workloads\"}[1m])) by (source_name)"
    }
   ]
  },
  {
   "title": "CPU by ingressgateway pod",
   "type": "graph",
   "description": "Percentage CPU utilization of the Istio IngressGateway pods.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "vCPU" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{job=\"kubernetes-cadvisor\",pod_name=~\"istio-ingressgateway-.*\",container_name=\"istio-proxy\"}[1m]) * 100",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Working Set Memory utilization of Istio IngressGateway proxies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "usage in megabytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{job=\"kubernetes-cadvisor\",pod_name=~\"istio-ingressgateway-.*\",container_name=\"istio-proxy\"} / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Number of routes",
   "type": "graph",
   "description": "The number of routes fetched from CC by cfroutesync",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Number of routes" }
   ],
   "targets": [
    { "expr": "cfroutesync_fetched_routes" }
   ]
  },
  {
   "title": "Seconds since last update to cfroutesync",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "idelta(cfroutesync_last_updated_at[1m])"
    }
   ]
  },
  {
   "title": "Envoy Update Failures",
   "type": "graph",
   "description": "Envoy CDS update failures can indicate that envoy isn't receiving updates from Istio control plane.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "failure rate" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_manager_cds_update_failure{app=\"istio-ingressgateway\"}[1m])"
    }
   ]
  }
 ]
}