resources:
  - name: cf-k8s-networking
    type: git
    icon: github
    source:
      uri: git@github.com:cloudfoundry/cf-k8s-networking.git
      branch: develop
      private_key: ((cf_k8s_networking_readwrite_deploy_key.private_key))

  - name: cf-k8s-networking-ci
    type: git
    icon: github
    source:
      uri: git@github.com:cloudfoundry/cf-k8s-networking.git
      branch: develop
      private_key: ((cf_k8s_networking_readwrite_deploy_key.private_key))
      paths:
        - ci/**

  - name: cf-for-k8s-ci
    type: git
    icon: github
    source:
      uri: git@github.com:cloudfoundry/cf-for-k8s
      private_key: ((cf_for_k8s_readonly_deploy_key.private_key))
      branch: develop
      paths:
        - ci/**

  - name: cf-k8s-networking-docker-images
    type: git
    icon: github
    source:
      branch: develop
      private_key: ((cf_k8s_networking_readwrite_deploy_key.private_key))
      uri: git@github.com:cloudfoundry/cf-k8s-networking.git
      paths:
        - ci/dockerfiles

  - name: upgrade-sidecars-image
    type: registry-image
    icon: docker
    source:
      repository: cloudfoundry/cf-k8s-networking-upgrade-sidecars
      username: ((dockerhub.username))
      password: ((dockerhub.password))

  - name: httpbin-repo
    type: git
    icon: github
    source:
      uri: git@github.com:cf-routing/httpbin.git
      branch: develop
      private_key: ((cf_k8s_networking_readwrite_deploy_key.private_key))

  - name: httpbin-image
    type: docker-image
    icon: docker
    source:
      repository: cfrouting/httpbin
      username: ((cf_k8s_networking_dockerhub.username))
      password: ((cf_k8s_networking_dockerhub.password))

  - name: proxy-repo
    type: git
    icon: github
    source:
      uri: git@github.com:cf-routing/proxy.git
      branch: develop
      private_key: ((cf_k8s_networking_readwrite_deploy_key.private_key))

  - name: proxy-image
    type: docker-image
    icon: docker
    source:
      repository: cfrouting/proxy
      username: ((cf_k8s_networking_dockerhub.username))
      password: ((cf_k8s_networking_dockerhub.password))

  - name: cf-for-k8s-develop
    type: git
    icon: github
    source:
      uri: git@github.com:cloudfoundry/cf-for-k8s
      private_key: ((cf_for_k8s_readwrite_deploy_key.private_key))
      branch: develop

  - name: dockerhub-retain-timer
    type: time
    source:
      interval: 3600h

jobs:
  - name: build-httpbin-image
    plan:
      - in_parallel:
        - get: httpbin-repo
          trigger: true
        - get: dockerhub-retain-timer
          trigger: true
      - put: httpbin-image
        params:
          build: httpbin-repo
          tag_as_latest: true

  - name: build-proxy-image
    plan:
      - in_parallel:
        - get: proxy-repo
          trigger: true
        - get: dockerhub-retain-timer
          trigger: true
      - put: proxy-image
        params:
          build: proxy-repo
          tag_as_latest: true

  - name: build-upgrade-sidecars-job-image
    plan:
      - in_parallel:
        - get: cf-for-k8s-develop
        - get: cf-k8s-networking
        - get: cf-for-k8s-ci
        - get: cf-k8s-networking-ci
        - get: cf-k8s-networking-docker-images
          trigger: true
      - in_parallel:
        - task: build-tag-file
          file: cf-k8s-networking-ci/ci/tasks/docker/build-tag-file-for-image.yml
        - task: build-labels-file
          file: cf-for-k8s-ci/ci/tasks/generate-oci-image-labels/task.yml
          input_mapping:
            source-repo: cf-k8s-networking
      - task: build-upgrade-sidecars-job-image
        privileged: true
        file: cf-k8s-networking-ci/ci/tasks/docker/build-oci-image.yml
        input_mapping:
          repository: cf-k8s-networking-docker-images
          image-labels-file: labels
        output_mapping:
          image: upgrade-sidecars-image
        params:
          CONTEXT: ci/dockerfiles/upgrade
          DOCKERFILE: ci/dockerfiles/upgrade/Dockerfile
          LABELS_FILE: image-labels-file/oci-image-labels
      - put: upgrade-sidecars-image
        params:
          image: upgrade-sidecars-image/image.tar
          additional_tags: docker-info/tags
      - task: updated-digest
        file: cf-k8s-networking-ci/ci/tasks/docker/update-image-digest-in-cf-for-k8s.yml
        params:
          COMPONENT_NAME: cf-k8s-networking-upgrade-sidecars
          TARGET_FILE: config/istio/upgrade-istio-sidecars-job.yml
        input_mapping:
          image-resource: upgrade-sidecars-image
      - put: cf-for-k8s-develop
        params:
          repository: cf-for-k8s-modified
          rebase: true
