---

resources:

- name: cf-for-k8s-master
  type: git
  icon: github-box
  source:
    uri: git@github.com:cloudfoundry/cf-for-k8s
    private_key: ((github_private_key.private_key))
    branch: master
    ignore_paths:
      - ci/**

- name: cf-k8s-networking
  type: git
  icon: github-box
  source:
    branch: master
    private_key: ((github_private_key.private_key))
    uri: git@github.com:cloudfoundry/cf-k8s-networking.git

- name: cf-k8s-networking-ci
  type: git
  icon: github-box
  source:
    branch: master
    private_key: ((github_private_key.private_key))
    uri: git@github.com:cloudfoundry/cf-k8s-networking.git
    paths:
      - ci
      - config

- name: cf-k8s-networking-istio-values
  type: git
  icon: github-box
  source:
    branch: master
    private_key: ((github_private_key.private_key))
    uri: git@github.com:cloudfoundry/cf-k8s-networking.git
    paths:
      - config/istio-install-config/istio-values.yaml

- name: cfroutesync-image-latest
  type: registry-image
  source:
    repository: gcr.io/cf-networking-images/cf-k8s-networking/cfroutesync
    tag: latest


- name: networking-oss-deployments
  type: git
  icon: github-box
  source:
    branch: master
    private_key: ((github_private_key.private_key))
    uri: git@github.com:cloudfoundry/networking-oss-deployments.git

- name: bosh-deployment
  type: git
  icon: github-box
  source:
    branch: master
    private_key: ((github_private_key.private_key))
    uri: git@github.com:cloudfoundry/bosh-deployment.git

- name: cf-deployment-concourse-tasks
  type: git
  icon: github-box
  source:
    branch: master
    private_key: ((github_private_key.private_key))
    uri: git@github.com:cloudfoundry/cf-deployment-concourse-tasks.git
    tag_filter: v*

- name: cf-deployment
  type: git
  icon: github-box
  source:
    uri: git@github.com:cloudfoundry/cf-deployment.git
    private_key: ((github_private_key.private_key))
    branch: release-candidate

- name: eirini-bosh-release-git
  type: git
  icon: github-box
  source:
    branch: terraform-k8s-version
    uri: git@github.com:angelachin/eirini-bosh-release.git
    private_key: ((github_private_key.private_key))

- name: istio
  type: git
  icon: github-box
  source:
    branch: 1.4.2
    uri: git@github.com:istio/istio.git
    private_key: ((github_private_key.private_key))

- name: metacontroller
  type: git
  icon: github-box
  source:
    branch: v0.4.0
    uri: git@github.com:GoogleCloudPlatform/metacontroller.git
    private_key: ((github_private_key.private_key))

- name: eirini-bosh-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-community/eirini-bosh-release

- name: bits-service-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/bits-service-release

- name: cfroutesync-image
  type: docker-image
  icon: docker
  source:
    repository: gcr.io/cf-networking-images/cf-k8s-networking/cfroutesync
    username: _json_key
    password: ((gcp_gcr_service_account_key))

groups:
  - name: eirini-dev-1
    jobs:
    - eirini-dev-1-bbl-up
    - eirini-dev-1-deploy-istio
    - eirini-dev-1-install-metacontroller
    - eirini-dev-1-install-cf-networking
    - eirini-dev-1-deploy-cf
  - name: build
    jobs:
      - run-units
      - publish-image
  - name: cf-for-k8s
    jobs:
      - dont-smoke-for-k8s-deploy-and-test
jobs:
# Build
- name: run-units
  plan:
    - in_parallel:
        - get: cf-k8s-networking
          trigger: true
        - get: cf-k8s-networking-ci
    - task: run-unit-tests
      file: cf-k8s-networking-ci/ci/tasks/tests/run-units.yml


- name: publish-image
  plan:
    - in_parallel:
        - get: cf-k8s-networking
          passed: [run-units]
          trigger: true
        - get: cf-k8s-networking-ci
    - task: build-tag-file
      file: cf-k8s-networking-ci/ci/tasks/docker/build-tag-file-for-image.yml
    - put: cfroutesync-image
      params:
        build: cf-k8s-networking/cfroutesync
        dockerfile: cf-k8s-networking/cfroutesync/deploy/Dockerfile
        additional_tags: docker-info/tags
        tag_as_latest: true

# Environment to run tests
- name: dont-smoke-for-k8s-deploy-and-test
  serial: true
  serial_groups: [dont-smoke-for-k8s]
  plan:
    - in_parallel:
        - get: cf-for-k8s-master
          trigger: true
        - get: cf-k8s-networking-ci
        - get: cf-k8s-networking
    - task: create-gke-cluster
      file: cf-k8s-networking-ci/ci/tasks/cf4k8s/create-gke-cluster.yml
      params:
        CLUSTER_NAME: &dont-smoke-for-k8s-cluster-name dont-smoke-for-k8s
        GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
    - task: install-cf
      file: cf-k8s-networking-ci/ci/tasks/cf4k8s/install-cf-for-k8s.yml
      params:
        CF_DOMAIN: &dont-smoke-for-k8s-domain "dont-smoke-for-k8s.routing.lol"
        CLUSTER_NAME: *dont-smoke-for-k8s-cluster-name
        GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
    - task: run-smoke-test
      file: cf-k8s-networking-ci/ci/tasks/cf4k8s/run-smoke-test.yml
    - task: generate-integration-configs
      file: cf-k8s-networking-ci/ci/tasks/cf4k8s/generate-integration-config.yml
    - task: networking-acceptance-gke-tests
      file: cf-k8s-networking-ci/ci/tasks/tests/run-networking-acceptance-gke.yml
      params:
        INTEGRATION_CONFIG_FILE: "config.json"
        CLUSTER_NAME: *dont-smoke-for-k8s-cluster-name
        GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
    - task: destroy-cluster
      file: cf-k8s-networking-ci/ci/tasks/cf4k8s/destroy-cluster.yml
      params:
        CF_DOMAIN: *dont-smoke-for-k8s-domain
        CLUSTER_NAME: *dont-smoke-for-k8s-cluster-name
        GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))


  # eirini-dev-1
- name: eirini-dev-1-bbl-up
  serial: true
  serial_groups: [eirini-dev-1]
  plan:
    - in_parallel:
        - get: cf-deployment-concourse-tasks
          resource: cf-deployment-concourse-tasks
        - get: cf-k8s-networking
        - get: cf-k8s-networking-ci
        - get: networking-oss-deployments
        - get: bosh-deployment
        - get: eirini-bosh-release-git
    - task: seed-bbl-env
      file: cf-k8s-networking-ci/ci/tasks/bbl/seed-env.yml
      input_mapping:
        bbl-state: networking-oss-deployments
      params:
        BBL_STATE_DIR: "environments/eirini-dev-1"
        SYSTEM_DOMAIN: &eirini-dev-1-domain "eirini-dev-1.routing.cf-app.com"
        APPS_DOMAIN: &eirini-dev-1-istio-domain "eirini-dev-1.routing.lol"
    - put: networking-oss-deployments
      params:
        repository: updated-bbl-state
        rebase: true
    - task: collect-ops-files
      file: cf-deployment-concourse-tasks/collect-ops-files/task.yml
      input_mapping:
        base-ops-files: bosh-deployment
        new-ops-files: cf-k8s-networking-ci
    - task: merge-bbl-config
      file: cf-k8s-networking-ci/ci/tasks/bbl/merge-bbl-config.yml
      params:
        SOURCE1_DIR: plan-patches/gcp
        SOURCE2_DIR: plan-patches/shared
        SOURCE3_DIR: ci/bbl-configs/add-parent-dns-full
        SOURCE4_DIR: ci/bbl-configs/eirini-scale-gke
      input_mapping:
        source1: eirini-bosh-release-git
        source2: eirini-bosh-release-git
        source3: cf-k8s-networking-ci
        source4: cf-k8s-networking-ci
    - task: bbl-up-eirini-dev-1
      file: cf-deployment-concourse-tasks/bbl-up/task.yml
      input_mapping:
        bbl-state: updated-bbl-state
        bbl-config: merged-bbl-config
      params: &bbl-up-eirini-dev-1-params
        BBL_CONFIG_DIR: .
        BBL_STATE_DIR: "environments/eirini-dev-1"
        BBL_IAAS: "gcp"
        BBL_LB_CERT: "certs/load-balancer/server.crt"
        BBL_LB_KEY: "certs/load-balancer/server.key"
        LB_DOMAIN: *eirini-dev-1-domain
        BBL_ENV_NAME: "eirini-dev-1"
        BBL_GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
        BBL_GCP_REGION: us-west1
      ensure:
        put: networking-oss-deployments
        params:
          repository: updated-bbl-state
          rebase: true

- name: eirini-dev-1-deploy-istio
  serial: true
  serial_groups: [eirini-dev-1]
  plan:
    - in_parallel:
        - get: istio
        - get: cf-k8s-networking
        - get: cf-k8s-networking-ci
        - get: cf-k8s-networking-istio-values
          trigger: true
        - get: networking-oss-deployments
          passed: [eirini-dev-1-bbl-up]
    - task: extract-kubeconfig
      file: cf-k8s-networking-ci/ci/tasks/k8s/extract-kubeconfig.yml
      input_mapping:
        bbl-state: networking-oss-deployments
      params:
        BBL_STATE_DIR: "environments/eirini-dev-1"
    - task: deploy-istio
      file: cf-k8s-networking-ci/ci/tasks/istio/deploy-istio.yml
      input_mapping:
        bbl-state: networking-oss-deployments
      params:
        KUBECONFIG_CONTEXT: "bosh-eirini-dev-1-cluster"
        SHARED_DNS_ZONE_NAME: "routing-lol"
        DNS_DOMAIN: "eirini-dev-1.routing.lol"
        GCP_DNS_SERVICE_ACCOUNT_KEY: ((gcp_dns_service_account_key))
        GCP_PROJECT_ID: "cf-routing"
    - task: install-grafana-dashboard
      file: cf-k8s-networking-ci/ci/tasks/istio/install-grafana-dashboard.yml
      input_mapping:
        bbl-state: networking-oss-deployments
      params:
        KUBECONFIG_CONTEXT: "bosh-eirini-dev-1-cluster"
    - task: enable-sidecar-injection
      file: cf-k8s-networking-ci/ci/tasks/istio/enable-sidecar-injection.yml
      params:
        KUBECONFIG_CONTEXT: "bosh-eirini-dev-1-cluster"

- name: eirini-dev-1-install-metacontroller
  serial: true
  serial_groups: [eirini-dev-1]
  plan:
    - in_parallel:
        - get: metacontroller
        - get: cf-k8s-networking
        - get: cf-k8s-networking-ci
        - get: networking-oss-deployments
          passed: [eirini-dev-1-bbl-up]
    - task: extract-kubeconfig
      file: cf-k8s-networking-ci/ci/tasks/k8s/extract-kubeconfig.yml
      input_mapping:
        bbl-state: networking-oss-deployments
      params:
        BBL_STATE_DIR: "environments/eirini-dev-1"
    - task: install-metacontroller
      file: cf-k8s-networking-ci/ci/tasks/k8s/kubectl-apply.yml
      input_mapping:
        bbl-state: networking-oss-deployments
        k8s-config-dir: metacontroller
      params:
        KUBECONFIG_CONTEXT: "bosh-eirini-dev-1-cluster"
        FILES_TO_APPLY: |
          manifests/metacontroller-namespace.yaml
          manifests/metacontroller-rbac.yaml
          manifests/metacontroller.yaml
- name: eirini-dev-1-install-cf-networking
  serial: true
  serial_groups: [eirini-dev-1]
  plan:
    - in_parallel:
        - get: cfroutesync-image-latest
        - get: cf-k8s-networking
        - get: cf-k8s-networking-ci
        - get: networking-oss-deployments
          passed: [eirini-dev-1-bbl-up]
    - task: extract-kubeconfig
      file: cf-k8s-networking-ci/ci/tasks/k8s/extract-kubeconfig.yml
      input_mapping:
        bbl-state: networking-oss-deployments
      params:
        BBL_STATE_DIR: "environments/eirini-dev-1"
    - task: install-cf-networking
      file: cf-k8s-networking-ci/ci/tasks/k8s/install-cf-networking.yml
      input_mapping:
        bbl-state: networking-oss-deployments
        cfroutesync-image: cfroutesync-image-latest
      params:
        KUBECONFIG_CONTEXT: "bosh-eirini-dev-1-cluster"
        BBL_STATE_DIR: "environments/eirini-dev-1"

- name: eirini-dev-1-deploy-cf
  serial: true
  serial_groups: [eirini-dev-1]
  plan:
    - in_parallel:
        - get: cf-deployment-concourse-tasks
          resource: cf-deployment-concourse-tasks
        - get: cf-deployment
          resource: cf-deployment
        - get: cf-k8s-networking-ci
        - get: networking-oss-deployments
          passed: [eirini-dev-1-bbl-up]
        - get: eirini-bosh-release
        - get: bits-service-release
        - get: cf-k8s-networking
    - task: upload-eirini-release-tarball
      file: cf-k8s-networking-ci/ci/tasks/bosh/upload-release.yml
      input_mapping:
        bbl-state: networking-oss-deployments
        release-tarball: eirini-bosh-release
      params:
        BBL_STATE_DIR: "environments/eirini-dev-1"
    - task: upload-bits-service-release-tarball
      file: cf-k8s-networking-ci/ci/tasks/bosh/upload-release.yml
      input_mapping:
        bbl-state: networking-oss-deployments
        release-tarball: bits-service-release
      params:
        BBL_STATE_DIR: "environments/eirini-dev-1"
    - task: eirini-dev-1-stemcell-upload
      file: cf-deployment-concourse-tasks/bosh-upload-stemcell-from-cf-deployment/task.yml
      input_mapping:
        bbl-state: networking-oss-deployments
      params:
        BBL_STATE_DIR: "environments/eirini-dev-1"
    - task: collect-ops-files
      file: cf-deployment-concourse-tasks/collect-ops-files/task.yml
      input_mapping:
        base-ops-files: cf-deployment
        new-ops-files: cf-k8s-networking-ci
      params:
        NEW_OPS_FILES: &eirini-dev-1-ops-to-collect |
          ci/cf-deployment-operations/capi-skip-cert-verify.yml
          ci/cf-deployment-operations/eirini/add-eirini.yml
          ci/cf-deployment-operations/eirini/hardcode-doppler-ip.yml
    - task: deploy
      file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
      input_mapping:
        bbl-state: networking-oss-deployments
        ops-files: collected-ops-files
        vars-files: networking-oss-deployments
      params:
        BBL_STATE_DIR: "environments/eirini-dev-1"
        SYSTEM_DOMAIN: *eirini-dev-1-domain
        OPS_FILES: &eirini-dev-1-ops-files |
          capi-skip-cert-verify.yml
          base-ops-files/operations/use-compiled-releases.yml
          base-ops-files/operations/bits-service/use-bits-service.yml
          add-eirini.yml
          hardcode-doppler-ip.yml
          base-ops-files/operations/override-app-domains.yml
          base-ops-files/operations/scale-to-one-az.yml
        VARS_FILES: |
          environments/eirini-dev-1/apps_domains_vars.yml
    - task: configure-eirini-bosh
      file: cf-deployment-concourse-tasks/run-errand/task.yml
      input_mapping:
        bbl-state: networking-oss-deployments
      params:
        ERRAND_NAME: configure-eirini-bosh
        BBL_STATE_DIR: "environments/eirini-dev-1"
