---

resources:

- name: cf-for-k8s-master
  type: git
  icon: github-box
  source:
    uri: git@github.com:cloudfoundry/cf-for-k8s
    private_key: ((github_private_key.private_key))
    branch: master
    ignore_paths:
      - ci/**

- name: cf-k8s-networking
  type: git
  icon: github-box
  source:
    branch: master
    private_key: ((github_private_key.private_key))
    uri: git@github.com:cloudfoundry/cf-k8s-networking.git
    ignore_paths:
      - config/values.yaml # Do not want resource to trigger on image digest updates

- name: cf-k8s-networking-values
  type: git
  icon: github-box
  source:
    branch: master
    private_key: ((github_private_key.private_key))
    uri: git@github.com:cloudfoundry/cf-k8s-networking.git

- name: cf-k8s-networking-ci
  type: git
  icon: github-box
  source:
    branch: master
    private_key: ((github_private_key.private_key))
    uri: git@github.com:cloudfoundry/cf-k8s-networking.git
    paths:
      - ci
      - config

- name: cfroutesync-image
  type: docker-image
  icon: docker
  source:
    repository: gcr.io/cf-networking-images/cf-k8s-networking/cfroutesync
    username: _json_key
    password: ((gcp_gcr_service_account_key))

- name: routecontroller-image
  type: docker-image
  icon: docker
  source:
    repository: gcr.io/cf-networking-images/cf-k8s-networking/routecontroller
    username: _json_key
    password: ((gcp_gcr_service_account_key))

- name: concourse-dcind
  type: git
  source:
    branch: master
    uri: git@github.com:karlkfi/concourse-dcind.git
    private_key: ((github_private_key.private_key))

groups:
  - name: build
    jobs:
      - run-cfroutesync-units
      - run-routecontroller-units
      - run-routecontroller-integration-tests
      - publish-cfroutesync-image
      - publish-routecontroller-image
  - name: dont-smoke
    jobs:
      - dont-smoke-for-k8s-deploy-and-test
jobs:
# Build
- name: run-cfroutesync-units
  plan:
    - in_parallel:
        - get: cf-k8s-networking
          trigger: true
        - get: cf-k8s-networking-ci
    - task: unit-tests
      file: cf-k8s-networking-ci/ci/tasks/tests/run-cfroutesync-units.yml

- name: run-routecontroller-units
  plan:
    - in_parallel:
        - get: cf-k8s-networking
          trigger: true
        - get: cf-k8s-networking-ci
    - task: unit-tests
      file: cf-k8s-networking-ci/ci/tasks/tests/run-routecontroller-units.yml

- name: run-routecontroller-integration-tests
  plan:
    - in_parallel:
        - get: cf-k8s-networking
          passed: [run-routecontroller-units]
          tags: [overlay-storage-driver]
          trigger: true
        - get: cf-k8s-networking-ci
          tags: [overlay-storage-driver]
        - get: concourse-dcind
          tags: [overlay-storage-driver]
    - task: integration-tests
      privileged: true
      tags: [overlay-storage-driver]
      file: cf-k8s-networking-ci/ci/tasks/tests/run-routecontroller-integration-tests.yml

- name: publish-cfroutesync-image
  plan:
    - in_parallel:
        - get: cf-k8s-networking
          passed: [run-cfroutesync-units]
          trigger: true
        - get: cf-k8s-networking-latest
          resource: cf-k8s-networking
        - get: cf-k8s-networking-ci
    - task: build-tag-file
      file: cf-k8s-networking-ci/ci/tasks/docker/build-tag-file-for-image.yml
    - put: cfroutesync-image
      params:
        build: cf-k8s-networking/cfroutesync
        dockerfile: cf-k8s-networking/cfroutesync/deploy/Dockerfile
        additional_tags: docker-info/tags
        tag_as_latest: true
    - task: add-updated-sha
      file: cf-k8s-networking-ci/ci/tasks/docker/add-updated-sha.yml
      input_mapping:
        image-resource: cfroutesync-image
        cf-k8s-networking: cf-k8s-networking-latest
      params:
        COMPONENT_NAME: cfroutesync
    # Put to a separate resource to avoid the pipeline getting this commit by
    # ignoring the config/values.yaml path. When putting to a git resource, the
    # commit is added to the concourse resource regardless of whether or not
    # the files that are committed are in ignore_paths. This should prevent a
    # cyclical commit loop.
    - put: cf-k8s-networking-values
      params:
        repository: cf-k8s-networking-modified

- name: publish-routecontroller-image
  plan:
    - in_parallel:
        - get: cf-k8s-networking
          passed: [run-routecontroller-integration-tests]
          trigger: true
        - get: cf-k8s-networking-latest
          resource: cf-k8s-networking
        - get: cf-k8s-networking-ci
    - task: build-tag-file
      file: cf-k8s-networking-ci/ci/tasks/docker/build-tag-file-for-image.yml
    - put: routecontroller-image
      params:
        build: cf-k8s-networking/routecontroller
        dockerfile: cf-k8s-networking/routecontroller/Dockerfile
        additional_tags: docker-info/tags
        tag_as_latest: true
    - task: add-updated-sha
      file: cf-k8s-networking-ci/ci/tasks/docker/add-updated-sha.yml
      input_mapping:
        image-resource: routecontroller-image
        cf-k8s-networking: cf-k8s-networking-latest
      params:
        COMPONENT_NAME: routecontroller
    # Put to a separate resource to avoid the pipeline getting this commit by
    # ignoring the config/values.yaml path. When putting to a git resource, the
    # commit is added to the concourse resource regardless of whether or not
    # the files that are committed are in ignore_paths. This should prevent a
    # cyclical commit loop.
    - put: cf-k8s-networking-values
      params:
        repository: cf-k8s-networking-modified

# Environment to run tests
- name: dont-smoke-for-k8s-deploy-and-test
  serial: true
  serial_groups: [dont-smoke-for-k8s]
  plan:
    - in_parallel:
        - get: cf-for-k8s-master
          trigger: true
        - get: cf-k8s-networking-ci
        - get: cf-k8s-networking
    - task: create-gke-cluster
      file: cf-k8s-networking-ci/ci/tasks/cf4k8s/create-gke-cluster.yml
      params:
        CLUSTER_NAME: &dont-smoke-for-k8s-cluster-name dont-smoke-for-k8s
        GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
    - task: install-cf
      file: cf-k8s-networking-ci/ci/tasks/cf4k8s/install-cf-for-k8s.yml
      params:
        CF_DOMAIN: &dont-smoke-for-k8s-domain "dont-smoke-for-k8s.routing.lol"
        CLUSTER_NAME: *dont-smoke-for-k8s-cluster-name
        GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
        KPACK_GCR_ACCOUNT_KEY: ((gcp_gcr_service_account_key))
    - task: run-smoke-test
      file: cf-k8s-networking-ci/ci/tasks/cf4k8s/run-smoke-test.yml
      params:
        SMOKE_TEST_SKIP_SSL: true
    - task: generate-integration-configs
      file: cf-k8s-networking-ci/ci/tasks/cf4k8s/generate-integration-config.yml
    - task: networking-acceptance-gke-tests
      file: cf-k8s-networking-ci/ci/tasks/tests/run-networking-acceptance-gke.yml
      params:
        INTEGRATION_CONFIG_FILE: "config.json"
        CLUSTER_NAME: *dont-smoke-for-k8s-cluster-name
        GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
    - task: destroy-cluster
      file: cf-k8s-networking-ci/ci/tasks/cf4k8s/destroy-cluster.yml
      params:
        CF_DOMAIN: *dont-smoke-for-k8s-domain
        CLUSTER_NAME: *dont-smoke-for-k8s-cluster-name
        GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
