---
resources:
- name: istio-release
  type: github-release
  icon: github-box
  source:
    owner: istio
    repository: istio
    tag_filter: '1\.6\..*'
    access_token: ((github_access_token))

- name: istio-proxyv2-image
  type: registry-image
  source:
    repository: docker.io/istio/proxyv2

- name: cf-networking-proxyv2-image
  type: registry-image
  source:
    repository: gcr.io/cf-routing/proxyv2
    username: _json_key
    password: ((shared_gcp_account_creds))

- name: istio-pilot-image
  type: registry-image
  source:
    repository: docker.io/istio/pilot

- name: cf-networking-pilot-image
  type: registry-image
  source:
    repository: gcr.io/cf-routing/pilot
    username: _json_key
    password: ((shared_gcp_account_creds))

- name: cf-k8s-networking-ci
  type: git
  icon: github-box
  source:
    branch: develop
    private_key: ((github_private_key.private_key))
    uri: git@github.com:cloudfoundry/cf-k8s-networking.git
    paths:
      - ci
      - config

- name: cf-k8s-networking
  type: git
  icon: github-box
  source:
    branch: develop
    private_key: ((github_private_key.private_key))
    uri: git@github.com:cloudfoundry/cf-k8s-networking.git

- name: cf-for-k8s-istio-bump-branch
  type: git
  icon: github-box
  source:
    branch: istio-version-bump
    private_key: ((github_private_key.private_key))
    uri: git@github.com:cloudfoundry/cf-for-k8s.git

- name: cf-for-k8s
  type: git
  icon: github-box
  source:
    uri: git@github.com:cloudfoundry/cf-for-k8s
    private_key: ((github_private_key.private_key))
    branch: master
    ignore_paths:
      - ci/**

jobs:
- name: pull-and-tag-istio-images
  serial_groups: ['bump-istio']
  plan:
  - in_parallel:
    - get: cf-k8s-networking-ci
    - get: istio-release
      trigger: true
    - get: istio-proxyv2-image
      resource: istio-proxyv2-image
      params:
        format: oci
    - get: istio-pilot-image
      resource: istio-pilot-image
      params:
        format: oci
  - task: prepare-repo
    # NOTE(ck,lh): Our goal is to have the Istio repo at the same commit the
    # release was created at. Normally, we would use the git concourse
    # resource; the git resource clones a single branch from a git repo.
    # However, Istio creates branches for its releases. If we use the git
    # resource to pull master, we may not have the release commit. If we use
    # the git resource to pull the current release branch, then we will need to
    # manually update this pipeline. In order to avoid missing commits and
    # manual updates, we are using a task instead. We are simply cloning the
    # repository manually in this task, and then passing it on as an output.
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: c2cnetworking/small-git
      inputs:
      - name: istio-release
      outputs:
      - name: istio-at-specified-sha
      run:
        path: /bin/bash
        args:
        - -cex
        - |
          git clone https://github.com/istio/istio.git ./istio-at-specified-sha
          pushd istio-at-specified-sha > /dev/null
            git checkout "$(cat ../istio-release/commit_sha)"
          popd
  - task: create-image-names
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: c2cnetworking/small-git
      inputs:
      - name: istio-release
      outputs:
      - name: pilot-image-name
      - name: proxyv2-image-name
      run:
        path: /bin/bash
        args:
        - -cex
        - |
          echo "index.docker.io/istio/pilot:$(cat istio-release/tag)" > pilot-image-name/name.txt
          echo "index.docker.io/istio/proxyv2:$(cat istio-release/tag)" > proxyv2-image-name/name.txt
  - task: annotate-istio-proxyv2
    file: cf-k8s-networking-ci/ci/tasks/docker/annotate.yml
    input_mapping:
      input-image-name: proxyv2-image-name
      repository: istio-at-specified-sha
    output_mapping:
      output-image: istio-proxyv2-annotated-image
  - task: annotate-istio-pilot
    file: cf-k8s-networking-ci/ci/tasks/docker/annotate.yml
    input_mapping:
      input-image-name: pilot-image-name
      repository: istio-at-specified-sha
    output_mapping:
      output-image: istio-pilot-annotated-image
  - in_parallel:
    - put: cf-networking-pilot-image
      params:
        image: istio-pilot-annotated-image/image.tar
        additional_tags: istio-release/tag
    - put: cf-networking-proxyv2-image
      params:
        image: istio-proxyv2-annotated-image/image.tar
        additional_tags: istio-release/tag

- name: generate-new-istio-config
  serial_groups: ['bump-istio']
  plan:
  - in_parallel:
    - get: cf-k8s-networking-ci
    - get: cf-for-k8s
    - get: istio-release
      trigger: true
      passed:
      - pull-and-tag-istio-images
  - task: generate-and-commit-config
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: gcr.io/cf-routing/cf-k8s-networking/k8s-deploy
      inputs:
      - name: istio-release
      - name: cf-for-k8s
      outputs:
      - name: cf-for-k8s
      run:
        path: /bin/bash
        args:
        - -cex
        - |
          pushd istio-release > /dev/null
            tar -xzvf istioctl-*-linux-amd64.tar.gz
            mv istioctl /usr/local/bin
          popd

          ISTIO_VERSION="$(cat istio-release/tag)"

          sed -i \
            "s/istio_version.*\$/istio_version: $ISTIO_VERSION/" \
            cf-for-k8s/build/istio/values.yaml

          cf-for-k8s/build/istio/build.sh

          pushd cf-for-k8s > /dev/null
            git config --global user.name "CF Networking Team CI Bot"
            git config --global user.email "CF-Networking@pivotal.io"
            git commit -a -m "Bump Istio to ${ISTIO_VERSION}"
          popd
  - put: cf-for-k8s-istio-bump-branch
    params:
      repository: cf-for-k8s
      tag_prefix: istio-bump-to-
      tag: istio-release/tag
      force: true


# Environment to run tests
- name: deploy-and-test-new-istio-version
  serial_groups: ['bump-istio']
  plan:
  - in_parallel:
    - get: cf-for-k8s
      resource: cf-for-k8s-istio-bump-branch
      trigger: true
      passed:
      - generate-new-istio-config
    - get: cf-k8s-networking-ci
    - get: cf-k8s-networking
  - task: create-gke-cluster
    file: cf-k8s-networking-ci/ci/tasks/cf4k8s/create-gke-cluster.yml
    params:
      CLUSTER_NAME: &ci-test-for-k8s-cluster-name bump-istio-test
      GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
  - task: install-cf
    file: cf-k8s-networking-ci/ci/tasks/cf4k8s/install-cf-for-k8s.yml
    params:
      CF_DOMAIN: &ci-test-for-k8s-domain "bump-istio-test.routing.lol"
      CLUSTER_NAME: *ci-test-for-k8s-cluster-name
      GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
      KPACK_GCR_ACCOUNT_KEY: ((gcp_gcr_service_account_key))
  - task: run-smoke-test
    file: cf-k8s-networking-ci/ci/tasks/cf4k8s/run-smoke-test.yml
    params:
      SMOKE_TEST_SKIP_SSL: true
  - task: generate-integration-configs
    file: cf-k8s-networking-ci/ci/tasks/cf4k8s/generate-integration-config.yml
  - task: networking-acceptance-gke-tests
    file: cf-k8s-networking-ci/ci/tasks/tests/run-networking-acceptance-gke.yml
    params:
      CLUSTER_NAME: *ci-test-for-k8s-cluster-name
      GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
      INTEGRATION_CONFIG_FILE: "config.json"
  - task: destroy-cluster
    file: cf-k8s-networking-ci/ci/tasks/cf4k8s/destroy-cluster.yml
    params:
      CF_DOMAIN: *ci-test-for-k8s-domain
      CLUSTER_NAME: *ci-test-for-k8s-cluster-name
      GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))

- name: push-tracker-stories
  serial_groups: ['bump-istio']
  plan:
  - in_parallel:
    - get: cf-k8s-networking-ci
    - get: istio-release
      trigger: true
  - task: create-public-tracker-story
    file: cf-k8s-networking-ci/ci/tasks/team/create-istio-bump-story.yml
    params:
      TRACKER_TOKEN: ((tracker_api_token))
  - task: create-private-tracker-story
    file: cf-k8s-networking-ci/ci/tasks/team/create-istio-osm-story.yml
    params:
      TRACKER_TOKEN: ((tracker_api_token))
