platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-for-k8s-ci

inputs:
  - name: cf-k8s-networking
  - name: cf-for-k8s-ci
  - name: image-resource

outputs:
  - name: cf-k8s-networking-modified

run:
  path: cf-k8s-networking-ci/ci/tasks/docker/add-updated-digest.sh

params:
  COMPONENT_NAME: # e.g. routecontroller
  GIT_COMMIT_USERNAME: "relint-ci"
  GIT_COMMIT_EMAIL: "cf-release-integration@pivotal.io"
