platform: linux

image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task

run:
  path: build

inputs:
- name: repository
  path: .
- name: image-labels-file

outputs:
- name: image

params:
  CONTEXT:
  DOCKERFILE:
  LABELS_FILE: /dev/null

