#!/usr/bin/env bash

set -euo pipefail

function printStatus {
      if [ $? -eq 0 ]; then
          echo -e "\nSWEET SUITE SUCCESS"
      else
          echo -e "\nSUITE FAILURE"
      fi
  }

trap printStatus EXIT


script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${script_dir}/.."

set -x

go vet ./...
go fmt ./...
go build -o /dev/null -v .

ginkgo -keepGoing -trace -progress -r -failOnPending -randomizeAllSpecs -p -race -skipPackage integration

# TODO run integration tests
