#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cfroutesync-config
  namespace: #@ data.values.systemNamespace
data:
  ccBaseURL: #@ data.values.cfroutesync.ccBaseURL
  uaaBaseURL: #@ data.values.cfroutesync.uaaBaseURL
  ccCA: #@ data.values.cfroutesync.ccCA
  uaaCA: #@ data.values.cfroutesync.uaaCA
  clientName: #@ data.values.cfroutesync.clientName
