platform: linux
image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-for-k8s-ci

inputs:
  - name: cf-for-k8s-ci
  - name: env-metadata

outputs:
  - name: integration-config

run:
  path: cf-for-k8s-ci/ci/tasks/cf-k8s-networking/generate-integration-config.sh
